// Inline style objects used across the app (referenced as S.<key>).
// Colors use CSS variables (shadcn tokens in index.css) so everything is
// theme-aware: light values ~match the original palette, and dark mode flips
// automatically when the `dark` class is on <html>.
import type { CSSProperties } from "react";
export const S: Record<string, CSSProperties> = {
  app:{display:"flex",minHeight:"100vh",background:"var(--background)",fontFamily:"'Segoe UI','Noto Sans Bengali',sans-serif"},
  sidebar:{width:230,background:"var(--sidebar)",color:"var(--sidebar-foreground)",display:"flex",flexDirection:"column",position:"sticky",top:0,height:"100vh",flexShrink:0},
  sidebarTop:{padding:"20px 16px 10px",borderBottom:"1px solid var(--sidebar-border)"},
  logoBox:{background:"var(--primary)",color:"var(--primary-foreground)",fontWeight:900,fontSize:13,borderRadius:7,padding:"4px 8px",display:"inline-block",marginBottom:6,letterSpacing:2},
  logoText:{fontSize:12,fontWeight:700,color:"var(--sidebar-foreground)",lineHeight:1.4},
  langRow:{display:"flex",gap:4,padding:"8px 16px"},
  langBtn:{flex:1,padding:"4px 8px",border:"1px solid var(--border)",background:"transparent",color:"var(--muted-foreground)",borderRadius:6,cursor:"pointer",fontSize:12},
  langOn:{background:"var(--primary)",color:"var(--primary-foreground)",borderColor:"var(--primary)"},
  nav:{flex:1,padding:"6px 8px",overflowY:"auto"},
  navBtn:{display:"flex",alignItems:"center",gap:10,width:"100%",padding:"9px 12px",background:"transparent",border:"none",color:"var(--muted-foreground)",borderRadius:8,cursor:"pointer",fontSize:13,textAlign:"left",marginBottom:2},
  navBtnOn:{background:"var(--primary)",color:"var(--primary-foreground)"},
  sidebarFoot:{padding:"12px 16px",borderTop:"1px solid var(--sidebar-border)"},
  userRow:{display:"flex",alignItems:"center",gap:10,marginBottom:8},
  ava:{width:34,height:34,borderRadius:"50%",background:"var(--primary)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:15,color:"var(--primary-foreground)",flexShrink:0},
  uName:{fontSize:13,fontWeight:600,color:"var(--foreground)"},
  uRole:{fontSize:11,color:"var(--muted-foreground)"},
  logoutBtn:{width:"100%",padding:"7px",background:"transparent",border:"1px solid var(--border)",color:"var(--muted-foreground)",borderRadius:6,cursor:"pointer",fontSize:13},
  main:{flex:1,overflowY:"auto",minWidth:0},
  page:{padding:"clamp(12px,3vw,24px)",maxWidth:960,margin:"0 auto"},
  ph:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:14,flexWrap:"wrap",gap:10},
  pt:{fontSize:"clamp(17px,4vw,22px)",fontWeight:800,color:"var(--foreground)",margin:0},
  ps:{fontSize:13,color:"var(--muted-foreground)",margin:"4px 0 0"},
  grid4:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:10,marginBottom:14},
  grid2:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:12,marginBottom:12},
  two:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16},
  statCard:{background:"var(--card)",color:"var(--card-foreground)",borderRadius:12,padding:"clamp(10px,2.5vw,18px)",boxShadow:"0 1px 3px rgba(0,0,0,0.08)",border:"1px solid var(--border)"},
  card:{background:"var(--card)",color:"var(--card-foreground)",borderRadius:12,padding:"clamp(12px,2.5vw,20px)",boxShadow:"0 1px 3px rgba(0,0,0,0.08)",marginBottom:16,border:"1px solid var(--border)"},
  ct:{fontSize:15,fontWeight:700,color:"var(--foreground)",marginBottom:14,marginTop:0},
  rankRow:{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:"1px solid var(--border)"},
  rankBadge:{width:26,height:26,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:12,flexShrink:0},
  addBtn:{padding:"9px 16px",background:"var(--primary)",color:"var(--primary-foreground)",border:"none",borderRadius:8,cursor:"pointer",fontSize:14,fontWeight:600},
  fg:{marginBottom:12},
  lbl:{display:"block",fontSize:13,fontWeight:600,color:"var(--foreground)",marginBottom:5},
  inp:{width:"100%",padding:"9px 12px",border:"1px solid var(--input)",borderRadius:8,fontSize:14,color:"var(--foreground)",background:"var(--background)",boxSizing:"border-box",outline:"none"},
  saveBtn:{padding:"9px 20px",background:"var(--primary)",color:"var(--primary-foreground)",border:"none",borderRadius:8,cursor:"pointer",fontSize:14,fontWeight:600},
  cancelBtn:{padding:"9px 20px",background:"var(--secondary)",color:"var(--secondary-foreground)",border:"none",borderRadius:8,cursor:"pointer",fontSize:14},
  submitBtn:{padding:"11px 28px",background:"var(--primary)",color:"var(--primary-foreground)",border:"none",borderRadius:8,cursor:"pointer",fontSize:15,fontWeight:700},
  tableWrap:{overflowX:"auto"},
  table:{width:"100%",borderCollapse:"collapse",fontSize:14},
  th:{padding:"10px 12px",textAlign:"left",background:"var(--muted)",color:"var(--muted-foreground)",fontWeight:600,fontSize:13,borderBottom:"2px solid var(--border)"},
  td:{padding:"9px 12px",color:"var(--foreground)",borderBottom:"1px solid var(--border)",verticalAlign:"middle"},
  mBtn:{padding:"5px 10px",border:"1px solid var(--border)",borderRadius:6,background:"var(--background)",color:"var(--muted-foreground)",cursor:"pointer",fontSize:13},
  mOn:{background:"var(--primary)",color:"var(--primary-foreground)",borderColor:"var(--primary)"},
  reportTab:{padding:"7px 14px",border:"1px solid var(--border)",borderRadius:20,background:"var(--background)",color:"var(--muted-foreground)",cursor:"pointer",fontSize:13},
  reportTabOn:{background:"var(--primary)",color:"var(--primary-foreground)",borderColor:"var(--primary)",fontWeight:700},
  scoreInp:{padding:"5px 4px",border:"1px solid var(--input)",borderRadius:6,fontSize:14,fontWeight:700,textAlign:"center",color:"var(--foreground)",background:"var(--background)",outline:"none",boxSizing:"border-box"},
  assignTag:{display:"inline-flex",alignItems:"center",gap:4,background:"var(--muted)",color:"var(--foreground)",padding:"3px 8px",borderRadius:20,fontSize:12,fontWeight:600},
  tagX:{background:"none",border:"none",cursor:"pointer",color:"var(--foreground)",fontSize:14,padding:"0 2px",lineHeight:1},
  sectionBox:{background:"var(--muted)",borderRadius:8,padding:"12px 14px",marginBottom:12},
  empty:{textAlign:"center",padding:32,color:"var(--muted-foreground)",fontSize:14},
  notif:{position:"fixed",top:20,right:20,color:"#fff",padding:"12px 20px",borderRadius:8,fontWeight:600,zIndex:999,boxShadow:"0 4px 12px rgba(0,0,0,0.15)",fontSize:14},
  modalBg:{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:998,padding:16},
  modalBox:{background:"var(--card)",color:"var(--card-foreground)",borderRadius:14,padding:"clamp(14px,4vw,24px)",width:"100%",maxWidth:440,boxShadow:"0 20px 60px rgba(0,0,0,0.25)",border:"1px solid var(--border)"},
  editInfoBox:{background:"var(--muted)",borderRadius:8,padding:"12px 14px",marginBottom:14},
  editInfoRow:{display:"flex",gap:8,padding:"4px 0",borderBottom:"1px solid var(--border)",fontSize:13},
  editInfoLabel:{color:"var(--muted-foreground)",minWidth:120,fontWeight:600},
  editInfoVal:{color:"var(--foreground)",flex:1},
  loginBg:{minHeight:"100vh",background:"linear-gradient(135deg,#0f172a 0%,#1e293b 50%,#4f46e5 100%)",display:"flex",alignItems:"center",justifyContent:"center",padding:12},
  loginCard:{background:"var(--card)",color:"var(--card-foreground)",borderRadius:16,padding:"clamp(16px,5vw,32px)",width:"100%",maxWidth:400,boxShadow:"0 20px 60px rgba(0,0,0,0.3)"},
  loginLogo:{display:"inline-block",background:"var(--primary)",color:"var(--primary-foreground)",fontWeight:900,fontSize:18,borderRadius:10,padding:"8px 16px",letterSpacing:3},
  loginBtn:{width:"100%",padding:12,background:"var(--primary)",color:"var(--primary-foreground)",border:"none",borderRadius:8,cursor:"pointer",fontSize:16,fontWeight:700,marginTop:4},
};
